### ISSUE TITLE
Create secrets in IRS repository

### ISSUE THREAD

**Issue by ds-ext-kmassalski** [eclipse-tractusx/sig-infra#397] opened 2024-01-02 14:02 UTC
**Is your support request related to a problem? Please describe.**  
Authentication was redisigned in IRS application and now we need new repository secrets to support it.

**Describe the solution you'd like**  
Please create the following secrets in repository https://github.com/catenax-ng/tx-item-relationship-service

Values can be found in Vault in 'traceability-irs' engine:
BETA_REGULAR_USER_API_KEY = beta/irs/apiKeyRegular
BETA_ADMIN_USER_API_KEY = beta/irs/apiKeyAdmin
DEV_REGULAR_USER_API_KEY = dev/irs/apiKeyRegular
DEV_ADMIN_USER_API_KEY = dev/irs/apiKeyAdmin 
DIL_REGULAR_USER_API_KEY = dil/irs/apiKeyRegular
DIL_ADMIN_USER_API_KEY = dil/irs/apiKeyAdmin 
INT_REGULAR_USER_API_KEY = int/irs/apiKeyRegular
INT_ADMIN_USER_API_KEY = int/irs/apiKeyAdmin

**Comment by almadigabor** [comment] 2024-01-03 08:22
Hey @ds-ext-kmassalski I've added the secrets, please check if they work as intended.

**Comment by FaGru3n** [comment] 2024-01-12 08:57
Hi @ds-ext-kmassalski  could we close this issue?

**Comment by FaGru3n** [comment] 2024-01-16 15:30
> INT_ADMIN_USER_API_KEY

also modified:
![image](https://github.com/eclipse-tractusx/sig-infra/assets/121097161/41b9e7d8-8ed5-408d-9502-e2626f19cb69)

Please review, thanks.

**Comment by ds-alexander-bulgakov** [comment] 2024-01-17 06:08
Hi @FaGru3n,
now the secrets are working fine. Thank you very much!
@ds-ext-kmassalski we can close this ticket if from your side everything is done.

**Comment by ds-alexander-bulgakov** [comment] 2024-01-24 08:28
Hi guys,
unfortunately this both secrets are not set correctly and i have to reopen this issue:
DIL_REGULAR_USER_API_KEY = dil/irs/apiKeyRegular
DIL_ADMIN_USER_API_KEY = dil/irs/apiKeyAdmin

Could you please have a look?

**Comment by ds-alexander-bulgakov** [comment] 2024-01-24 08:56
Thank you @almadigabor! I will check and update the ticket.

**Comment by ds-alexander-bulgakov** [comment] 2024-01-24 11:30
@almadigabor could you please check again if they are set correctly? I tried and checked on our side several times but the authentication is still not working even though the secrets themself are valid for local executions.

**Comment by ds-alexander-bulgakov** [comment] 2024-01-25 12:41
Hi @almadigabor, any updates on this?

**Comment by almadigabor** [comment] 2024-01-26 09:05
Hey @ds-alexander-bulgakov! Sorry for the delay, I've updated the secrets. Can you check again?

**Comment by ds-alexander-bulgakov** [comment] 2024-01-29 13:31
Hi @almadigabor,
the secrets are correct now. Thank you very much! Ticket will be closed.

**Closed by ds-alexander-bulgakov** 2024-01-29 13:31 UTC
Labels: support
